# Configuration for probot-stale - https://github.com/probot/stale

limitPerRun: 30

pulls:
  daysUntilStale: 14
  exemptProjects: true
  exemptMilestones: true
  staleLabel: abandoned
  exemptLabels:
    - needs review
    - on hold

  markComment: >
    Labeling this pull request (PR) as abandoned since it has gone 14 days or more
    since the last update. An abandoned PR can be continued by another contributor.
    The abandoned label will be removed if work on this PR is taken up again.

issues:
  daysUntilStale: 30
  daysUntilClose: 40
  exemptProjects: true
  exemptMilestones: true
  staleLabel: needs more information
  exemptLabels:
    - bug
    - enhancement
    - tests
    - documentation
    - on hold
    - new module submission
    - module proposal

  markComment: >
    This issue has been automatically marked as needs more information because
    it has not had activity from the community in the last 30 days. It will be
    closed if no further activity occurs within 10 days. If the issue is label
    with any of the work labels (e.g bug, enhancement, documentation, or tests)
    the issue will not auto-close.

  closeComment: >
    This issue has be automatically close because it is has not had activity from
    the community in the last 40 days.
