[ClassVersion("1.0.0.0"), FriendlyName("ResourceName")]
class MSFT_ResourceName : OMI_BaseResource
{
    [Key, Description("Descriptive text for this property")] String MandatoryParameter;
    [Write, Description("Descriptive text for this property")] String NonMandatoryParameter;
    [Write, Description("Specifies if the ... should be present or absent. Default value is 'Present'."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
};
