#---------------------------------# 
#      environment configuration  # 
#---------------------------------# 
version: 2.3.0.{build}
os: WMF 5
install:
  - ps: . .\AppVeyor\AppVeyorInstall.ps1

environment:
  nugetKey:
    secure: cTU7bDH5E95cI/Zj36CfMrrgnnW/fmEd1S9+cqmBlV3P0GMUnluLcydTWgDK7Usu
  github_access_token:
    secure: Xk7jTkdE82qskQy9WPZK0zSafSjT6gK1SYxH8m4Aa8muCMQ4ACkkztJ3toh9DFlS
  ModuleName: cChoco
#---------------------------------# 
#      build configuration        # 
#---------------------------------# 
build_script: 
  - ps: . .\AppVeyor\AppVeyorBuild.ps1

#---------------------------------# 
#      test configuration         # 
#---------------------------------# 
test_script: 
  - ps: . .\AppVeyor\AppVeyorTest.ps1

#---------------------------------# 
#      deployment configuration   # 
#---------------------------------# 
deploy_script: 
  - ps: . .\AppVeyor\AppveyorDeploy.ps1